default:
  image: node:18.17.1

deploy-preview:
  stage: deploy
  except:
    - main
  before_script:
    - npm install --global vercel
  script:
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

deploy-production:
  stage: deploy
  only:
    - main
  before_script:
    - npm install --global vercel
  script:
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN